### ISSUE TITLE
Node Mapnik source links broken

### ISSUE THREAD

**Issue by mapsam** [mapnik/documentation#6]
Currently the source link URLs are 404s: 

```
https://github.com/mapnik/documentation/blob/2007848f1b4b49be176f9d9542d822372ef471ec/node_modules/mapnik/src/mapnik_featureset.cpp#L6-L12
```

gotta fix em!

Looks like the `--github` source flag is based on the current repository the documentation is being built in.

**Comment by pnorman** [comment]
using a tag instead of sha would also help with understandable URLs
